export function createInitialState() {
    return {
        animationFrameId: undefined,
        audioOffsetSec: 0,
        audioPlayer: new Audio(),
        audioWaiting: false,
        cachedViewportWidth: 0,
        cancelVideoExport: false,
        currentBpm: 120,
        defaultBgColor: "#000000",
        defaultNoteColor: "#ffffff",
        elapsedBeforePause: 0,
        enableFlyin: true,
        globalAudioFile: null,
        globalAudioOnsetSec: null,
        globalMidiPpq: 480,
        globalMidiTempos: [],
        globalScoreHeight: 500,
        globalSystemBarlineScreenX: 0,
        globalSystemInternalX: 0,
        globalTimeSigs: [],
        globalZoom: 1.0,
        isAudioLoaded: false,
        isExportingVideoMode: false,
        isFinished: false,
        isMidiLoaded: false,
        isPlaying: false,
        lastHighlightedIndex: -1,
        lastRenderClock: 0,
        lastUiUpdateTime: 0,
        mapData: [],
        midiDurationSec: 0,
        playbackSimTime: 0,
        playlineRatio: 0.5,
        renderQueue: [],
        scanGlowRange: 100,
        showHighlights: true,
        showPlayline: true,
        showScanGlow: true,
        startTime: 0,
        stickyMinX: 0,
        svgTags: [],
    };
}
